/// Created from: C:\ISC\doc\projects\Facturae\xsd_32\Facturaev3_2.xml
Class Facturae.v32.CorrectionMethodDescriptionType Extends %String [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 0;

Parameter MAXLEN;

Parameter NAMESPACE = "http://www.facturae.es/Facturae/2009/v3.2/Facturae";

Parameter VALUELIST = ",Rectificación íntegra,Rectificación por diferencias,Rectificación por descuento por volumen de operaciones durante un periodo,Autorizadas por la Agencia Tributaria";

}
