/// Created from: C:\ISC\doc\projects\Facturae\xsd_32\Facturaev3_2.xml
Class Facturae.v32.LanguageCodeType Extends %String [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 0;

Parameter MAXLEN;

Parameter NAMESPACE = "http://www.facturae.es/Facturae/2009/v3.2/Facturae";

Parameter VALUELIST = ",ar,be,bg,ca,cs,da,de,el,en,es,et,eu,fi,fr,ga,gl,hr,hu,is,it,lv,lt,mk,mt,nl,no,pl,pt,ro,ru,sk,sl,sq,sr,sv,tr,uk";

}
