/// Created from: C:\ISC\doc\projects\Facturae\xsd_32\Facturaev3_2.xml
Class Facturae.v32.ReasonDescriptionType Extends %String [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 0;

Parameter MAXLEN;

Parameter NAMESPACE = "http://www.facturae.es/Facturae/2009/v3.2/Facturae";

Parameter VALUELIST = ",Número de la factura,Serie de la factura,Fecha expedición,Nombre y apellidos/Razón Social-Emisor,Nombre y apellidos/Razón Social-Receptor,Identificación fiscal Emisor/obligado,Identificación fiscal Receptor,Domicilio Emisor/Obligado,Domicilio Receptor,Detalle Operación,Porcentaje impositivo a aplicar,Cuota tributaria a aplicar,Fecha/Periodo a aplicar,Clase de factura,Literales legales,Base imponible,Cálculo de cuotas repercutidas,Cálculo de cuotas retenidas,Base imponible modificada por devolución de envases / embalajes,Base imponible modificada por descuentos y bonificaciones,Base imponible modificada por resolución firme, judicial o administrativa,Base imponible modificada cuotas repercutidas no satisfechas. Auto de declaración de concurso";

}
